GET http://localhost:3000/api/v1/usuarios HTTP/1.1

###

POST http://localhost:3000/api/v1/usuarios HTTP/1.1
Content-Type: application/json

{
    "name": "unach6",
    "password": "soap6"
}

###
POST http://localhost:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "name": "unach4",
    "password": "soap4"
}
